name: site generate test

# on:
#   push:
#     branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    needs: test262

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Download sample artifacts
      run: |
        curl -L -o artifacts.zip https://github.com/CanadaHonk/test262-page/raw/main/testing/test262_sample_artifacts.zip
        mkdir results
        unzip artifacts.zip -d results

    - name: Generate site
      run: node site/generate.mjs

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: site

  deploy:
    needs: generate

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2