name: Run test262 in all engines and publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ ".github/workflows/run.yml", "scripts/**/*", "helpers/**/*" ]

jobs:
  test262:
    runs-on: ubuntu-22.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        engine: [v8, jsc, sm, chakra, hermes, libjs, engine262, qjs, xs, graaljs, nashorn, rhino, babel, swc] # all
        # engine: [v8, jsc, sm, chakra, hermes, libjs, qjs, xs, graaljs] # exclude hangers/long
        # engine: [chakra, graaljs, jsc, libjs, qjs, xs] # all fast
        # engine: [v8, jsc, sm, chakra] # just major
        # engine: [jsc] # just jsc

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    # - uses: actions/setup-java@v3
    #   if: ${{ matrix.engine == 'graaljs' }}
    #   with:
    #     distribution: 'oracle'
    #     java-version: '18'

    # - name: Install Java
    #   if: ${{ matrix.engine == 'graaljs' }}
    #   run: sudo apt install openjdk-18-jdk

    - name: Run test262 with ${{ matrix.engine }}
      run: ./scripts/engines/${{ matrix.engine }}.sh

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.engine }}
        path: |
          results.json
          jsvu.json
          esvu.json
          time.txt
          version.txt
          test262-rev.txt

    - name: Download results
      uses: actions/download-artifact@v3
      with:
        path: results

    - name: Download old results
      run: |
        # node scripts/downloadOldResults.mjs
        sh scripts/extractResults.sh

    - name: Generate site
      run: node site/generate.mjs

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      continue-on-error: true
      with:
        path: site

    - name: Deploy to GitHub Pages
      id: deployment
      continue-on-error: true
      uses: actions/deploy-pages@v2
